import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [i,setValue] = useState(0)

  const btn = (value)=>{

    setValue(value)

  }

  const array = [
    {
      img:"/red.png",
      color:"#A5023B"
    },
    {
      img:'/neon green (1).png',
      color:'#13BA53'
    },{
      img:"/Untitled-2.png",
      color:'#6A095D'
    }
  ]
  return (
    <>
      <Head>
        <title>JORDAN PAGE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
          


<div className="items-center justify-center flex">
  <div className="boxContainer h-[550px] w-[1000px] mt-[50px] " style={{borderTopLeftRadius:'20px',borderBottomLeftRadius:'20px',background:'url("/red.png")',backgroundRepeat:'none',backgroundSize:'cover'}}>
  <div className='h-full w-full bg-black opacity-95 relative overflow-hidden'>
  <Navbar/>
<div className='contentContainer  items-center justify-center '>
  <div className='absolute left-0 right-0 w-full' style={{zIndex:2}}> <h1 className='text-[#161616] text-[210px] font-extrabold tracking-wider'>JORDAN</h1></div>
  <Image src="/navigation bar.png" width={8} height={100} alt="shoe" className="absolute right-[35px] top-[235px]" style={{zIndex:3}}/>
  <div className="jordanShoe absolute left-0 right-0 w-full flex items-center justify-center ml-[50px]" style={{zIndex:5}}> 
  <div style={{ZIndex:8}} className="absolute left-[50px] top-[80px]"><h2 className={` text-[110px] font-extrabold tracking-normal mb-0`} style={{color:`${array[i].color}`}}>Jump</h2>
  <p className='text-center tracking-widest -mt-[1px] absolute -bottom-[10px] left-0 ' style={{letterSpacing:'14px',zIndex:10}}>Basketball Shoe</p></div>
   <Image src={array[i].img} width={1300} height={200} alt="shoe" className="-mt-[120px] -ml-[40px]" style={{zIndex:3}}/>
   <div style={{zIndex:1}} className="absolute right-[130px] top-[90px]">
    <h3  style={{color:`${array[i].color}`}} className="ml-[200px] -mb-[30px] font-extrabold absolute top-[30px] right-0">2021 PF</h3>
    <h2 className='text-[120px] tracking-wider font-extrabold'>man</h2>
    <div className='flex gap-[10px]'>
    <div className='flex'>
      <div><h3 style={{color:`${array[i].color}`}} className="font-extrabold text-2xl">134$</h3 ></div>
      <div><h3 className='text-sm font-extrabold'>JORDAN</h3><h4 className='text-sm font-extrabold'>JUMPMAN 2021 PF</h4></div>
      </div>

      <div><button style={{background:`${array[i].color}`}} className="text-white p-2 rounded-2xl">exclusive</button></div>
    </div>
   
    
    </div>
   
   </div>

   
</div>




<div className='bottom absolute bottom-0 p-4 flex justify-between items-center' style={{display:'flex',justifyContent:'space-between'}}>
  <div className='shoesContainer flex mr-[50px]'>
   <span onClick={()=>btn(0)} className="cursor-pointer w-[10px] h-[10px]" style={{zIndex:99}}>1</span><Image src="/red.png" width={70} height={80} alt="shoe" />
    <span onClick={()=>btn(1)} className="cursor-pointer w-[10px] h-[10px]" style={{zIndex:99}}>2</span><Image src="/neon green (1).png" width={80} height={100} alt="shoe"  />
 <span onClick={()=>btn(2)} className="cursor-pointer w-[10px] h-[10px]" style={{zIndex:99}}>3</span><Image src="/Untitled-2.png" width={80} height={100} alt="shoe" />

  </div>

  <div className='flex items-center gap-[20px]'>
    <button className='bg-white text-black h-[35px] w-[130px] text-sm font-extrabold flex items-center justify-center'>ADD TO CART</button>    <button  className='bg-transparent text-white h-[35px] w-[130px] text-sm font-extrabold border-[1px] border-white flex items-center justify-center'>BUY NOW</button>
  </div>
  <div className='ml-[70px]'>
    <h2 className='font-extrabold'>INSPIRATION</h2>
    <p className='w-[350px] text-sm'>Inspired by the design of the latest Air Jordan game shoe, the Jordan Jumpman 2021 helps up-and-coming players level up their game. </p>
  </div>

</div>



  </div>
  </div>
</div>
       
          
    </>
  )
}
